name: test_env
channels:
  - pytorch
dependencies:
  - python=3.9
  - spyder
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - natsort
  - matplotlib
  - qtconsole=5.1.1
  - scikit-learn
  - dill
  - h5py
  - boto3
  - scipy
  - statsmodels
  - pip
  - pip:
    - wandb
    - mne
